### PR TITLE
Rest basics

### PR DESCRIPTION
**Pull request by Gi60s**
I've added a document that outlines REST best practices as defined by the industry. The file does not reference the UAPI spec but is relevant in that REST consumers and producers need to know what status codes and methods indicate in a REST API.

### CODE REVIEW

**Comment by brentmoore** [comment]
Do we have a source for this to attribute in the document?

Also, the versioning section is slightly different from what we do with WSO2. We may want to adjust it to match.

**Comment by Gi60s** [comment]
What do we do with the WSO2 versioning?

Also, I'll work on getting some references.

**Comment by Gi60s** [comment]
I believe this is now ready.

**Comment by Gi60s** [comment]
Actually, lets hold on the merge. I may add a section about about resource naming, plural vs singular. Plus I have something to add after our round table discussion in the delete section.

**Review by joshgubler — APPROVED** [review]

**Pull request merged**
